field: e804d8bd-d5b1-471e-90b5-ebbc8061dc77 # Entries
fieldLayouts:
  dc049f24-321c-4f0d-b5de-9e3977002b65:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5d2565e3-3b77-43db-bc40-08e1e0caa0fd # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef59fdbc-19b3-4649-b2d4-60e524360113
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8af52c0f-b765-4e98-868d-585293bcc775 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f671085-912a-4e87-b892-734e427505dd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0fe19bf0-3aff-42c3-affd-25e1a20ea4b9
        userCondition: null
fields:
  5d2565e3-3b77-43db-bc40-08e1e0caa0fd: # Text
    columnSuffix: unrgcjzc
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8af52c0f-b765-4e98-868d-585293bcc775: # Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonLink
    instructions: null
    name: Link
    searchable: false
    settings:
      allowCustomText: false
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: true
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: true
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
handle: entry
name: Entry
sortOrder: 1
