field: e6f93d8e-5b47-4a03-83f7-9290e9953254 # Entries
fieldLayouts:
  b7c5d424-efd1-45d0-a374-8bd13033079b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7ba0c79d-00f3-49cc-9b31-996f41f67719 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2d223d5-be1c-466f-9dc3-209dd94a9d3f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1bd66386-7f31-47d1-a653-2465b7d82eee # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77921a5f-58b1-443e-aecd-dcd4dad87243
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7fe1ef01-0bfc-4283-8b0a-47e280d0a809
        userCondition: null
fields:
  1bd66386-7f31-47d1-a653-2465b7d82eee: # Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonLink
    instructions: null
    name: Link
    searchable: false
    settings:
      allowCustomText: false
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: true
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: true
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  7ba0c79d-00f3-49cc-9b31-996f41f67719: # Text
    columnSuffix: pdjgllty
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: entry
name: Entry
sortOrder: 1
