fieldLayouts:
  8436b866-2aaa-4764-946e-d2043e301542:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5cdf9b54-71a4-4f76-a6ef-722f8fbec365
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ce2c25fb-97fd-44f0-afd4-01e2befb850b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 60ac7fa8-c37f-4d88-95cf-4c48388790b1 # Page Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee3e7235-e176-49f7-bbae-f686df3b74df
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9d71a558-ce47-4b46-b7f0-daab5682ece4
        userCondition: null
handle: contact
hasTitleField: false
name: Contact
section: a77f50f9-d430-4728-8635-58d63c511a0d # Contact
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
