fieldLayouts:
  6c6d86a1-b51b-4297-ae87-90f725dc6ec6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0ae01cca-7ee2-4ec3-bd04-0522e0966e96
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b0e313f2-3eb8-452f-8778-781a3fa3cba5 # Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9ba343a-cfa1-41aa-9644-708aca1c9114
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 60ac7fa8-c37f-4d88-95cf-4c48388790b1 # Page Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75b80094-3372-4ea0-92ef-6f4efbaf7bcc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3a57381d-c4de-45ee-aa8d-3b0abe3bfa89
        userCondition: null
handle: demo
hasTitleField: false
name: Demo
section: 2847712c-6c72-4c74-8f64-e4f9c4966b65 # Demo
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
