fieldLayouts:
  d1acf4a7-d5c9-4c87-b1a6-eabb3641a3ac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 323e81f8-bfb9-4307-954e-f8d25249b5c1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b0e313f2-3eb8-452f-8778-781a3fa3cba5 # Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4b0a4b9-7221-4e59-866e-ae5cb09c65de
            userCondition: null
            warning: null
            width: 100
        name: Core
        uid: 444fbaa4-6f03-4f0f-9d41-d1b9629e151f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 60ac7fa8-c37f-4d88-95cf-4c48388790b1 # Page Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e7dd91b-8112-4f46-ac48-9a9a0fed33e2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7d5394a1-6f80-4b8a-9553-2a0699f8aad1
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 32f42829-0214-4294-9ec7-67c3b9f1b8d4 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
