columnSuffix: null
contentColumnType: string
fieldGroup: 8c7497c4-d88f-4731-9af0-7cccfc3509a2 # Components
handle: pageBuilder
instructions: null
name: 'Page Builder'
searchable: false
settings:
  contentTable: '{{%matrixcontent_pagebuilder}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
