changedFieldIndicator: 849155735
field: e4478cd8-f7ef-49e1-84f9-a39f159df298 # Row
fieldLayouts:
  f65da13c-9bd4-4ea7-9fcd-e9d5b4bcf41f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f97c7428-87a8-406b-b233-6eaed9b40530 # Images
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0247bb51-1a53-49d6-9d07-c8136e65c8d6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bd89add9-9008-4e69-a403-d6abb0ee292a # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 290cbfda-8efc-4161-95c1-06f7dd09a2fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: df27dbbb-dc1e-4b87-accb-dc9ef881d11b # Mirror
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5158ed5c-8018-4797-8cc6-cd1f1a49f4be
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 02b3ba7a-674d-4718-872f-62dde2921dc1
        userCondition: null
fields:
  bd89add9-9008-4e69-a403-d6abb0ee292a: # Layout
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: galleryLayout
    instructions: 'Allows for greater control of the image flow in the gallery, please refer to the CMS Guide for examples'
    name: Layout
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 50/50
            -
              - value
              - fiftyFifty
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 60/40
            -
              - value
              - sixtyForty
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 25/25/50
            -
              - value
              - twentyFiveTwentyFiveFifty
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 25/50/25
            -
              - value
              - twentyFiveFiftyTwentyFive
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  df27dbbb-dc1e-4b87-accb-dc9ef881d11b: # Mirror
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: galleryMirror
    instructions: 'Allows for mirroring of specified layout variations 60/40 selected, mirror enabled, 40/60 rendered on the frontend'
    name: Mirror
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f97c7428-87a8-406b-b233-6eaed9b40530: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: galleryImages
    instructions: null
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:ae7e798c-f7c8-4b4f-a496-6c85bb112906' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 3
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:ae7e798c-f7c8-4b4f-a496-6c85bb112906' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
