changedFieldIndicator: 45122537
field: 3437d8bd-188e-42be-b494-53f131545535 # Buttons
fieldLayouts:
  f31cdd7e-8aa5-42a7-a31b-f31a7be282e6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e6f93d8e-5b47-4a03-83f7-9290e9953254 # Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e182909c-fe4a-48c8-b962-e40aa09855b7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7bc85628-214e-4476-826b-06f3f0b44913
        userCondition: null
fields:
  e6f93d8e-5b47-4a03-83f7-9290e9953254: # Entries
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: null
    name: Entries
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_entries_1}}'
      maxBlocks: 2
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
