name: Deployment

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'

jobs:
  build:
    name: Deployment
    
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout Repo files
      uses: actions/checkout@v2
      
    - name: Deploy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "*"
        target: "${{ secrets.REMOTE_TARGET }}"
        rm: false