name: Deployment to remote server

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'

jobs:
  build:
    name: Deployment
    
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    
    steps:

    - run: ls -la

    - name: Checkout Repo files
      uses: actions/checkout@v2

    - run: sudo apt-get install rsync

    - name: Deploy to Server
      uses: Pendect/action-rsyncer@v1.1.0
      env:
          DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
      with:
          flags: '-avc'
          src: '*'
          dest: '${{ secrets.REMOTE_USER }}@"${{ secrets.REMOTE_HOST }}":${{ secrets.REMOTE_TARGET }}'
  install:
    name: Set Permissions
    needs: build
    runs-on: ubuntu-20.04
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/craft/basic-craftcms
          composer update
          composer install
          sudo chmod -R 774 ${{ secrets.REMOTE_TARGET }}
          