name: Deployment to remote server

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'

jobs:
  build:
    name: Deployment
    
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    
    steps:

    - run: ls -la

    - name: Checkout Repo files
      uses: actions/checkout@v2

    - run: sudo apt-get install rsync

    - name: Deploy to Server
      uses: Pendect/action-rsyncer@v1.1.0
      env:
          DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
      with:
          flags: '-avc --delete'
          src: '*'
          dest: '${{ secrets.REMOTE_USER }}@"${{ secrets.REMOTE_HOST }}":/home/craft/basic-craftcms'
  install:
    - name: Run composer
      needs: build
      run: composer install
